#!/usr/bin/perl
#
# Some defines
#

*BINDIR = \'%CGIBIN%';
*FILEDIR = \'%TRACKDIR%';
*DATABASE = \'%DATABASE%';
*MYSQLHOST = \'%MYSQLHOST%';
*MYSQLUSER = \'%MYSQLUSER%';
*MYSQLPASSWORD = \'%MYSQLPASSWORD%';

1;

