version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8.2
  INSTALL_NODE_VERSION: 12

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_production
      target: production
      args:
        <<: *build_args
    command: gunicorn -b :5000 -w ${GUNICORN_WORKERS} -k gevent 'airscore.app:create_app()'
    image: master-image
    container_name: ${FLASK_CONTAINER}
    ports:
      - "5000:5000"
    environment:
      REDIS_CONTAINER: ${REDIS_CONTAINER}
      WEB_SERVER_CONTAINER: ${WEB_SERVER_CONTAINER}
      FLASK_CONTAINER: ${FLASK_CONTAINER}
      FLASK_PORT: ${FLASK_PORT}
      REDIS_URL: redis://${REDIS_CONTAINER}:6379
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      RQ_QUEUE: ${RQ_QUEUE}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ADMINS: ${ADMINS}
      MYSQLHOST: ${MYSQLHOST}
      DATABASE: ${DATABASE}
      MYSQLUSER: ${MYSQLUSER}
      MYSQLPASSWORD: ${MYSQLPASSWORD}
      DATABASE_URI: mysql+pymysql://${MYSQLUSER}:${MYSQLPASSWORD}@${MYSQLHOST}/${DATABASE}
      XCONTEST_USER: ${XCONTEST_USER}
      XCONTEST_PASS: ${XCONTEST_PASS}
      TELEGRAM_API: ${TELEGRAM_API}
      TELEGRAM_CHANNEL: ${TELEGRAM_CHANNEL}
    networks:
      - net
    restart: always
    <<: *default_volumes

  worker:
    image: master-image
    depends_on:
      - redis
    command: rqworker --with-scheduler --name worker --url redis://${REDIS_CONTAINER}:6379/0 ${RQ_QUEUE}
    environment:
      FLASK_CONTAINER: ${FLASK_CONTAINER}
      FLASK_PORT: ${FLASK_PORT}
      REDIS_URL: redis://${REDIS_CONTAINER}:6379
      RQ_QUEUE: ${RQ_QUEUE}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MYSQLHOST: ${MYSQLHOST}
      DATABASE: ${DATABASE}
      MYSQLUSER: ${MYSQLUSER}
      MYSQLPASSWORD: ${MYSQLPASSWORD}
      DATABASE_URI: mysql+pymysql://${MYSQLUSER}:${MYSQLPASSWORD}@${MYSQLHOST}/${DATABASE}
      XCONTEST_USER: ${XCONTEST_USER}
      XCONTEST_PASS: ${XCONTEST_PASS}
      TELEGRAM_API: ${TELEGRAM_API}
      TELEGRAM_CHANNEL: ${TELEGRAM_CHANNEL}
    networks:
      - net
    <<: *default_volumes
  # uncomment to have a another worker
  #  worker2:
  #    image: master-image
  #    depends_on:
  #      - redis
  #    command: rqworker --name worker2 --url redis://redis:6379/0

  redis:
    image: redis
    container_name: ${REDIS_CONTAINER}
    networks:
      - net

  nginx:
    container_name: ${WEB_SERVER_CONTAINER}
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - net
    volumes:
      - type: bind
        source: ./airscore/static
        target: /static
volumes:
  node-modules:
  static-build:

networks:
  net:


#
#  dashboard:
#    image: master-image
#    ports:
#      - 5555:5555
#    depends_on:
#      - redis
#    command: rq-dashboard --port 5555 --redis-url redis://redis:6379/0

