version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8.2
  INSTALL_NODE_VERSION: 12

services:
  manage:
    build:
      context: .
      target: manage
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      REDIS_URL: redis://redis:6379
      REDIS_CONTAINER: redis
      WEB_SERVER_CONTAINER: dummy
      FLASK_CONTAINER: flask_dev
      FLASK_PORT: 3214
      MAIL_SERVER: dummy
      MAIL_PORT: 123
      MAIL_USE_TLS: 0
      MAIL_USE_SSL: 0
      MAIL_USERNAME: dummy
      MAIL_PASSWORD: dummy
      ADMINS: dummy
      MYSQLHOST: dummy
      DATABASE: dummy
      MYSQLUSER: dummy
      MYSQLPASSWORD: dummy
      XCONTEST_USER: dummy
      XCONTEST_PASS: dummy
      TELEGRAM_API: dummy
      TELEGRAM_CHANNEL: dummy
    image: "airscore-manage"
    container_name: manage
    stdin_open: true
    tty: true
