version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8.2
  INSTALL_NODE_VERSION: 12

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./dev.db:/tmp/dev.db

services:
  tests:
    build:
      context: .
      target: tests
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      FLASK_APP: autoapp.py
      SECRET_KEY: not-so-secret
      SECURITY_PASSWORD_SALT: my_precious_two
      SEND_FILE_MAX_AGE_DEFAULT: 0
#      PYTHONPATH: ${app}:src
      REDIS_URL: redis://redis:6379
      REDIS_CONTAINER: redis
      WEB_SERVER_CONTAINER: dummy
      FLASK_CONTAINER: flask_dev
      FLASK_PORT: 3214
      MAIL_SERVER: dummy
      MAIL_PORT: 123
      MAIL_USE_TLS: false
      MAIL_USE_SSL: false
      MAIL_USERNAME: dummy
      MAIL_PASSWORD: dummy
      ADMINS: dummy
      MYSQLHOST: dummy
      DATABASE: dummy
      MYSQLUSER: dummy
      MYSQLPASSWORD: dummy
      DATABASE_URI: test
      XCONTEST_USER: dummy
      XCONTEST_PASS: dummy
      TELEGRAM_API: dummy
      TELEGRAM_CHANNEL: dummy
      REDIS_CONTAINER: dummy
      WEB_SERVER_CONTAINER: dummy
      FLASK_CONTAINER: airscore_prod
      FLASK_PORT: 5000
      RQ_QUEUE: dummy

    image: "airscore-manage"
    container_name: tests
    stdin_open: true
    tty: true
    <<: *default_volumes

volumes:
  node-modules:
  static-build:
  dev-db:
